### PR TITLE
Add imagePullSecrets

### PR DESCRIPTION
**Pull request by palcoberro**
Allows to reference to one or more secrets to be used when pulling images
ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### CODE REVIEW

**Review by ckotzbauer — CHANGES_REQUESTED** [review]
Could you please fix the "lint-test" check? The changes do not pass the linter currently.
In general, it LGTM :+1:

**Comment by palcoberro** [comment]
@ckotzbauer I fixed the linting errors but I'm still having a problem during the tests:

`Error: invalid argument "600" for "--timeout" flag: time: missing unit in duration 600`

do you know how to fix it? Many thanks in advance

**Comment by ckotzbauer** [comment]
That's a error not related to your changes. I changed the parameter in master branch. Could you rebase your PR? Then it should work...

**Comment by ckotzbauer** [comment]
Thanks for your help!

**Pull request merged**
